// Copyright © 2026 CCP ehf.

#include "StdAfx.h"

#if ( TRINITY_PLATFORM == TRINITY_VULKAN )

#include "VulkanFormats.h"

using namespace Tr2RenderContextEnum;

namespace TrinityALImpl
{

VkFormat ToVkFormat( PixelFormat format )
{
	switch( format )
	{
	case PIXEL_FORMAT_R32G32B32A32_TYPELESS:
		return VK_FORMAT_R32G32B32A32_SFLOAT;
	case PIXEL_FORMAT_R32G32B32A32_FLOAT:
		return VK_FORMAT_R32G32B32A32_SFLOAT;
	case PIXEL_FORMAT_R32G32B32A32_UINT:
		return VK_FORMAT_R32G32B32A32_UINT;
	case PIXEL_FORMAT_R32G32B32A32_SINT:
		return VK_FORMAT_R32G32B32A32_SINT;
	case PIXEL_FORMAT_R32G32B32_TYPELESS:
		return VK_FORMAT_R32G32B32_SFLOAT;
	case PIXEL_FORMAT_R32G32B32_FLOAT:
		return VK_FORMAT_R32G32B32_SFLOAT;
	case PIXEL_FORMAT_R32G32B32_UINT:
		return VK_FORMAT_R32G32B32_UINT;
	case PIXEL_FORMAT_R32G32B32_SINT:
		return VK_FORMAT_R32G32B32_SINT;
	case PIXEL_FORMAT_R16G16B16A16_TYPELESS:
		return VK_FORMAT_R16G16B16A16_SFLOAT;
	case PIXEL_FORMAT_R16G16B16A16_FLOAT:
		return VK_FORMAT_R16G16B16A16_SFLOAT;
	case PIXEL_FORMAT_R16G16B16A16_UNORM:
		return VK_FORMAT_R16G16B16A16_UNORM;
	case PIXEL_FORMAT_R16G16B16A16_UINT:
		return VK_FORMAT_R16G16B16A16_UINT;
	case PIXEL_FORMAT_R16G16B16A16_SNORM:
		return VK_FORMAT_R16G16B16A16_SNORM;
	case PIXEL_FORMAT_R16G16B16A16_SINT:
		return VK_FORMAT_R16G16B16A16_SINT;
	case PIXEL_FORMAT_R32G32_TYPELESS:
		return VK_FORMAT_R32G32_SFLOAT;
	case PIXEL_FORMAT_R32G32_FLOAT:
		return VK_FORMAT_R32G32_SFLOAT;
	case PIXEL_FORMAT_R32G32_UINT:
		return VK_FORMAT_R32G32_UINT;
	case PIXEL_FORMAT_R32G32_SINT:
		return VK_FORMAT_R32G32_SINT;
	case PIXEL_FORMAT_R32G8X24_TYPELESS:
		return VK_FORMAT_D32_SFLOAT_S8_UINT;
	case PIXEL_FORMAT_D32_FLOAT_S8X24_UINT:
		return VK_FORMAT_D32_SFLOAT_S8_UINT;
	case PIXEL_FORMAT_R32_FLOAT_X8X24_TYPELESS:
		return VK_FORMAT_D32_SFLOAT_S8_UINT;
	case PIXEL_FORMAT_X32_TYPELESS_G8X24_UINT:
		return VK_FORMAT_D32_SFLOAT_S8_UINT;
	case PIXEL_FORMAT_R10G10B10A2_TYPELESS:
		return VK_FORMAT_A2B10G10R10_UNORM_PACK32;
	case PIXEL_FORMAT_R10G10B10A2_UNORM:
		return VK_FORMAT_A2B10G10R10_UNORM_PACK32;
	case PIXEL_FORMAT_R10G10B10A2_UINT:
		return VK_FORMAT_A2B10G10R10_UINT_PACK32;
	case PIXEL_FORMAT_R11G11B10_FLOAT:
		return VK_FORMAT_B10G11R11_UFLOAT_PACK32;
	case PIXEL_FORMAT_R8G8B8A8_TYPELESS:
		return VK_FORMAT_R8G8B8A8_UNORM;
	case PIXEL_FORMAT_R8G8B8A8_UNORM:
		return VK_FORMAT_R8G8B8A8_UNORM;
	case PIXEL_FORMAT_R8G8B8A8_UNORM_SRGB:
		return VK_FORMAT_R8G8B8A8_SRGB;
	case PIXEL_FORMAT_R8G8B8A8_UINT:
		return VK_FORMAT_R8G8B8A8_UINT;
	case PIXEL_FORMAT_R8G8B8A8_SNORM:
		return VK_FORMAT_R8G8B8A8_SNORM;
	case PIXEL_FORMAT_R8G8B8A8_SINT:
		return VK_FORMAT_R8G8B8A8_SINT;
	case PIXEL_FORMAT_R16G16_TYPELESS:
		return VK_FORMAT_R16G16_SFLOAT;
	case PIXEL_FORMAT_R16G16_FLOAT:
		return VK_FORMAT_R16G16_SFLOAT;
	case PIXEL_FORMAT_R16G16_UNORM:
		return VK_FORMAT_R16G16_UNORM;
	case PIXEL_FORMAT_R16G16_UINT:
		return VK_FORMAT_R16G16_UINT;
	case PIXEL_FORMAT_R16G16_SNORM:
		return VK_FORMAT_R16G16_SNORM;
	case PIXEL_FORMAT_R16G16_SINT:
		return VK_FORMAT_R16G16_SINT;
	case PIXEL_FORMAT_R32_TYPELESS:
		return VK_FORMAT_R32_SFLOAT;
	case PIXEL_FORMAT_D32_FLOAT:
		return VK_FORMAT_D32_SFLOAT;
	case PIXEL_FORMAT_R32_FLOAT:
		return VK_FORMAT_R32_SFLOAT;
	case PIXEL_FORMAT_R32_UINT:
		return VK_FORMAT_R32_UINT;
	case PIXEL_FORMAT_R32_SINT:
		return VK_FORMAT_R32_SINT;
	case PIXEL_FORMAT_R24G8_TYPELESS:
		return VK_FORMAT_D24_UNORM_S8_UINT;
	case PIXEL_FORMAT_D24_UNORM_S8_UINT:
		return VK_FORMAT_D24_UNORM_S8_UINT;
	case PIXEL_FORMAT_R24_UNORM_X8_TYPELESS:
		return VK_FORMAT_D24_UNORM_S8_UINT;
	case PIXEL_FORMAT_X24_TYPELESS_G8_UINT:
		return VK_FORMAT_D24_UNORM_S8_UINT;
	case PIXEL_FORMAT_R8G8_TYPELESS:
		return VK_FORMAT_R8G8_UNORM;
	case PIXEL_FORMAT_R8G8_UNORM:
		return VK_FORMAT_R8G8_UNORM;
	case PIXEL_FORMAT_R8G8_UINT:
		return VK_FORMAT_R8G8_UINT;
	case PIXEL_FORMAT_R8G8_SNORM:
		return VK_FORMAT_R8G8_SNORM;
	case PIXEL_FORMAT_R8G8_SINT:
		return VK_FORMAT_R8G8_SINT;
	case PIXEL_FORMAT_R16_TYPELESS:
		return VK_FORMAT_R16_SFLOAT;
	case PIXEL_FORMAT_R16_FLOAT:
		return VK_FORMAT_R16_SFLOAT;
	case PIXEL_FORMAT_D16_UNORM:
		return VK_FORMAT_D16_UNORM;
	case PIXEL_FORMAT_R16_UNORM:
		return VK_FORMAT_R16_UNORM;
	case PIXEL_FORMAT_R16_UINT:
		return VK_FORMAT_R16_UINT;
	case PIXEL_FORMAT_R16_SNORM:
		return VK_FORMAT_R16_SNORM;
	case PIXEL_FORMAT_R16_SINT:
		return VK_FORMAT_R16_SINT;
	case PIXEL_FORMAT_R8_TYPELESS:
		return VK_FORMAT_R8_UNORM;
	case PIXEL_FORMAT_R8_UNORM:
		return VK_FORMAT_R8_UNORM;
	case PIXEL_FORMAT_R8_UINT:
		return VK_FORMAT_R8_UINT;
	case PIXEL_FORMAT_R8_SNORM:
		return VK_FORMAT_R8_SNORM;
	case PIXEL_FORMAT_R8_SINT:
		return VK_FORMAT_R8_SINT;
	case PIXEL_FORMAT_A8_UNORM:
		return VK_FORMAT_R8_UNORM;
	case PIXEL_FORMAT_R9G9B9E5_SHAREDEXP:
		return VK_FORMAT_E5B9G9R9_UFLOAT_PACK32;
	case PIXEL_FORMAT_BC1_TYPELESS:
		return VK_FORMAT_BC1_RGBA_UNORM_BLOCK;
	case PIXEL_FORMAT_BC1_UNORM:
		return VK_FORMAT_BC1_RGBA_UNORM_BLOCK;
	case PIXEL_FORMAT_BC1_UNORM_SRGB:
		return VK_FORMAT_BC1_RGBA_SRGB_BLOCK;
	case PIXEL_FORMAT_BC2_TYPELESS:
		return VK_FORMAT_BC2_UNORM_BLOCK;
	case PIXEL_FORMAT_BC2_UNORM:
		return VK_FORMAT_BC2_UNORM_BLOCK;
	case PIXEL_FORMAT_BC2_UNORM_SRGB:
		return VK_FORMAT_BC2_SRGB_BLOCK;
	case PIXEL_FORMAT_BC3_TYPELESS:
		return VK_FORMAT_BC3_UNORM_BLOCK;
	case PIXEL_FORMAT_BC3_UNORM:
		return VK_FORMAT_BC3_UNORM_BLOCK;
	case PIXEL_FORMAT_BC3_UNORM_SRGB:
		return VK_FORMAT_BC3_SRGB_BLOCK;
	case PIXEL_FORMAT_BC4_TYPELESS:
		return VK_FORMAT_BC4_UNORM_BLOCK;
	case PIXEL_FORMAT_BC4_UNORM:
		return VK_FORMAT_BC4_UNORM_BLOCK;
	case PIXEL_FORMAT_BC4_SNORM:
		return VK_FORMAT_BC4_SNORM_BLOCK;
	case PIXEL_FORMAT_BC5_TYPELESS:
		return VK_FORMAT_BC5_UNORM_BLOCK;
	case PIXEL_FORMAT_BC5_UNORM:
		return VK_FORMAT_BC5_UNORM_BLOCK;
	case PIXEL_FORMAT_BC5_SNORM:
		return VK_FORMAT_BC5_SNORM_BLOCK;
	case PIXEL_FORMAT_B5G6R5_UNORM:
		return VK_FORMAT_R5G6B5_UNORM_PACK16;
	case PIXEL_FORMAT_B5G5R5A1_UNORM:
		return VK_FORMAT_A1R5G5B5_UNORM_PACK16;
	case PIXEL_FORMAT_B8G8R8A8_UNORM:
		return VK_FORMAT_B8G8R8A8_UNORM;
	case PIXEL_FORMAT_B8G8R8X8_UNORM:
		return VK_FORMAT_B8G8R8A8_UNORM;
	case PIXEL_FORMAT_B8G8R8A8_TYPELESS:
		return VK_FORMAT_B8G8R8A8_UNORM;
	case PIXEL_FORMAT_B8G8R8A8_UNORM_SRGB:
		return VK_FORMAT_B8G8R8A8_SRGB;
	case PIXEL_FORMAT_B8G8R8X8_TYPELESS:
		return VK_FORMAT_B8G8R8A8_UNORM;
	case PIXEL_FORMAT_B8G8R8X8_UNORM_SRGB:
		return VK_FORMAT_B8G8R8A8_SRGB;
	case PIXEL_FORMAT_BC6H_TYPELESS:
		return VK_FORMAT_BC6H_UFLOAT_BLOCK;
	case PIXEL_FORMAT_BC6H_UF16:
		return VK_FORMAT_BC6H_UFLOAT_BLOCK;
	case PIXEL_FORMAT_BC6H_SF16:
		return VK_FORMAT_BC6H_SFLOAT_BLOCK;
	case PIXEL_FORMAT_BC7_TYPELESS:
		return VK_FORMAT_BC7_UNORM_BLOCK;
	case PIXEL_FORMAT_BC7_UNORM:
		return VK_FORMAT_BC7_UNORM_BLOCK;
	case PIXEL_FORMAT_BC7_UNORM_SRGB:
		return VK_FORMAT_BC7_SRGB_BLOCK;
	default: // UNKNOWN, R1_UNORM, R8G8_B8G8/G8R8_G8B8 (4:2:2), R10G10B10_XR_BIAS_A2
		return VK_FORMAT_UNDEFINED;
	}
}

bool IsDepthFormat( PixelFormat format )
{
	switch( ToVkFormat( format ) )
	{
	case VK_FORMAT_D16_UNORM:
	case VK_FORMAT_D32_SFLOAT:
	case VK_FORMAT_D24_UNORM_S8_UINT:
	case VK_FORMAT_D32_SFLOAT_S8_UINT:
		return true;
	default:
		return false;
	}
}

bool IsStencilFormat( PixelFormat format )
{
	VkFormat vk = ToVkFormat( format );
	return vk == VK_FORMAT_D24_UNORM_S8_UINT || vk == VK_FORMAT_D32_SFLOAT_S8_UINT;
}

VkImageAspectFlags AspectMask( PixelFormat format )
{
	if( !IsDepthFormat( format ) )
	{
		return VK_IMAGE_ASPECT_COLOR_BIT;
	}
	return VK_IMAGE_ASPECT_DEPTH_BIT | ( IsStencilFormat( format ) ? VK_IMAGE_ASPECT_STENCIL_BIT : 0 );
}

}

#endif
